// collections.go stores Kometa-style Plex Collection definitions
// (DESIGN.md §11.11), mirroring playlists.go's shape: a thin row pointing
// at a real Plex object, not a duplicated item cache - Plex itself remains
// the source of truth for membership.
package db

import (
	"database/sql"
	"encoding/json"
	"time"
)

// Collection mirrors the collections table.
type Collection struct {
	ID               int64
	UserID           int64
	ServerID         int64
	LibrarySectionID string
	LibraryType      string // Plex's own "movie" | "show" | "artist"
	PlexCollectionID sql.NullString
	Name             string
	Description      sql.NullString
	BuilderType      string         // "smart" | "manual"
	Rules            sql.NullString // JSON []Rule, used when BuilderType == "smart"
	ManualItems      sql.NullString // JSON []string (Plex ratingKeys), used when BuilderType == "manual"
	SyncMode         string         // "sync" | "add_only"
	SortTitle        sql.NullString // optional Plex sort title override
	DynamicSetID     sql.NullInt64  // set when generated by a dynamic_collections set (see GenerateDynamicCollections)
	DynamicKey       sql.NullString // the facet value this row was generated for, when DynamicSetID is set
	CreatedAt        int64
	UpdatedAt        int64
}

// Rule is one flat (field, operator, value) filter row - collections
// support AND-combined rules only, no OR/nesting (DESIGN.md §11.11).
type Rule struct {
	Field    string `json:"field"`
	Operator string `json:"operator"`
	Value    string `json:"value"`
}

func (c Collection) ParsedRules() []Rule {
	var rules []Rule
	if c.Rules.Valid {
		_ = json.Unmarshal([]byte(c.Rules.String), &rules)
	}
	return rules
}

func (c Collection) ParsedManualItems() []string {
	var items []string
	if c.ManualItems.Valid {
		_ = json.Unmarshal([]byte(c.ManualItems.String), &items)
	}
	return items
}

// ExternalListSource is the JSON shape stored in Collection.Rules when
// BuilderType == "external_list" (DESIGN.md §11.11's external list/chart
// builder) - Rules is reused rather than adding a new column, same as it
// already holds a different shape ([]Rule) for BuilderType == "smart".
// Provider picks which service to pull from; Mode further picks which of
// that provider's endpoints (only TMDb has more than one, "list" is the
// only mode the other three providers support); ListID only applies to
// Mode == "list".
type ExternalListSource struct {
	Provider string `json:"provider"` // "tmdb" | "imdb" | "tvdb" | "letterboxd"
	Mode     string `json:"mode"`     // "list" | "popular" | "top_rated"
	ListID   string `json:"listId"`
	Limit    int    `json:"limit"`
}

func (c Collection) ParsedExternalListSource() ExternalListSource {
	var src ExternalListSource
	if c.Rules.Valid {
		_ = json.Unmarshal([]byte(c.Rules.String), &src)
	}
	if src.Provider == "" {
		src.Provider = "tmdb"
	}
	return src
}

const collectionCols = "id, user_id, server_id, library_section_id, library_type, plex_collection_id, name, description, builder_type, rules, manual_items, sync_mode, sort_title, dynamic_set_id, dynamic_key, created_at, updated_at"

func scanCollection(row interface{ Scan(...any) error }) (*Collection, error) {
	var c Collection
	err := row.Scan(&c.ID, &c.UserID, &c.ServerID, &c.LibrarySectionID, &c.LibraryType, &c.PlexCollectionID, &c.Name, &c.Description, &c.BuilderType, &c.Rules, &c.ManualItems, &c.SyncMode, &c.SortTitle, &c.DynamicSetID, &c.DynamicKey, &c.CreatedAt, &c.UpdatedAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	return &c, nil
}

// CreateCollection inserts a collection definition row. rulesJSON/
// manualItemsJSON are raw JSON strings (or empty) matching whichever of
// them applies to builderType.
func CreateCollection(sqlDB *sql.DB, userID, serverID int64, librarySectionID, libraryType, name, description, builderType, rulesJSON, manualItemsJSON, syncMode string) (*Collection, error) {
	now := time.Now().Unix()
	res, err := sqlDB.Exec(
		`INSERT INTO collections (user_id, server_id, library_section_id, library_type, name, description, builder_type, rules, manual_items, sync_mode, created_at, updated_at)
		 VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
		userID, serverID, librarySectionID, libraryType, name, nullIfEmpty(description), builderType, nullIfEmpty(rulesJSON), nullIfEmpty(manualItemsJSON), syncMode, now, now,
	)
	if err != nil {
		return nil, err
	}
	id, err := res.LastInsertId()
	if err != nil {
		return nil, err
	}
	return GetCollectionByID(sqlDB, id)
}

func GetCollectionByID(sqlDB *sql.DB, id int64) (*Collection, error) {
	return scanCollection(sqlDB.QueryRow("SELECT "+collectionCols+" FROM collections WHERE id = ?", id))
}

func GetUserCollections(sqlDB *sql.DB, userID int64) ([]Collection, error) {
	rows, err := sqlDB.Query("SELECT "+collectionCols+" FROM collections WHERE user_id = ? ORDER BY created_at DESC", userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Collection
	for rows.Next() {
		c, err := scanCollection(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *c)
	}
	return out, rows.Err()
}

// CollectionUpdate is a partial update - nil fields are left untouched,
// mirroring ScheduleUpdate's convention.
type CollectionUpdate struct {
	Name        *string
	Description *string
	BuilderType *string
	Rules       *string // raw JSON, nil means "don't touch"
	ManualItems *string
	SyncMode    *string
	SortTitle   *string
}

func UpdateCollection(sqlDB *sql.DB, id int64, u CollectionUpdate) error {
	fields := []string{}
	values := []any{}
	if u.Name != nil {
		fields = append(fields, "name = ?")
		values = append(values, *u.Name)
	}
	if u.Description != nil {
		fields = append(fields, "description = ?")
		values = append(values, nullIfEmpty(*u.Description))
	}
	if u.BuilderType != nil {
		fields = append(fields, "builder_type = ?")
		values = append(values, *u.BuilderType)
	}
	if u.Rules != nil {
		fields = append(fields, "rules = ?")
		values = append(values, nullIfEmpty(*u.Rules))
	}
	if u.ManualItems != nil {
		fields = append(fields, "manual_items = ?")
		values = append(values, nullIfEmpty(*u.ManualItems))
	}
	if u.SyncMode != nil {
		fields = append(fields, "sync_mode = ?")
		values = append(values, *u.SyncMode)
	}
	if u.SortTitle != nil {
		fields = append(fields, "sort_title = ?")
		values = append(values, nullIfEmpty(*u.SortTitle))
	}
	if len(fields) == 0 {
		return nil
	}
	fields = append(fields, "updated_at = ?")
	values = append(values, time.Now().Unix())
	values = append(values, id)
	q := "UPDATE collections SET "
	for i, f := range fields {
		if i > 0 {
			q += ", "
		}
		q += f
	}
	q += " WHERE id = ?"
	_, err := sqlDB.Exec(q, values...)
	return err
}

// UpdateCollectionPlexID sets the real Plex collection ratingKey once the
// first successful refresh creates it - mirrors UpdatePlaylistPlexID.
func UpdateCollectionPlexID(sqlDB *sql.DB, id int64, plexCollectionID string) error {
	_, err := sqlDB.Exec("UPDATE collections SET plex_collection_id = ?, updated_at = ? WHERE id = ?", plexCollectionID, time.Now().Unix(), id)
	return err
}

func TouchCollection(sqlDB *sql.DB, id int64) error {
	_, err := sqlDB.Exec("UPDATE collections SET updated_at = ? WHERE id = ?", time.Now().Unix(), id)
	return err
}

func DeleteCollection(sqlDB *sql.DB, id int64) error {
	_, err := sqlDB.Exec("DELETE FROM collections WHERE id = ?", id)
	return err
}

// CreateGeneratedCollection inserts a smart collection row on behalf of a
// dynamic collection set (GenerateDynamicCollections) - a separate insert
// from CreateCollection rather than widening its parameter list, since only
// dynamic-set-generated rows ever populate dynamic_set_id/dynamic_key/
// sort_title at creation time.
func CreateGeneratedCollection(sqlDB *sql.DB, dyn DynamicCollection, name, sortTitle, dynamicKey, rulesJSON string) (*Collection, error) {
	now := time.Now().Unix()
	res, err := sqlDB.Exec(
		`INSERT INTO collections (user_id, server_id, library_section_id, library_type, name, builder_type, rules, manual_items, sync_mode, sort_title, dynamic_set_id, dynamic_key, created_at, updated_at)
		 VALUES (?, ?, ?, ?, ?, 'smart', ?, '[]', 'sync', ?, ?, ?, ?, ?)`,
		dyn.UserID, dyn.ServerID, dyn.LibrarySectionID, dyn.LibraryType, name, rulesJSON, nullIfEmpty(sortTitle), dyn.ID, dynamicKey, now, now,
	)
	if err != nil {
		return nil, err
	}
	id, err := res.LastInsertId()
	if err != nil {
		return nil, err
	}
	return GetCollectionByID(sqlDB, id)
}

// GetGeneratedCollections returns every collection row a dynamic set has
// generated so far, keyed by their DynamicKey for GenerateDynamicCollections
// to diff against the current facet keys.
func GetGeneratedCollections(sqlDB *sql.DB, dynamicSetID int64) ([]Collection, error) {
	rows, err := sqlDB.Query("SELECT "+collectionCols+" FROM collections WHERE dynamic_set_id = ?", dynamicSetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Collection
	for rows.Next() {
		c, err := scanCollection(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *c)
	}
	return out, rows.Err()
}
